# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e274e7b9ca8e5626b3d5e937ebde19d3d0b38f02465e201a7bba390919e498d40dce6eb6569bea98ad19b9bf9be9f0a5d1980227d8cf334a37ca23844bebfb9c

test:
  secret_key_base: 9419a124f4bd764f63c33a0be709a4c1e12f9e44dc1fd36468f811f6d85fbbba20176570368d44ee33b6b3762097368773fbf410c4b4bcffe3651a96728f808e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
